# Social Network Ads Sales Prediction using Machine Leanring

# Project Flow
1 getting data                                     
2 preprocessing data                                   
3 train test split                                     
4 using 4 classifers algorithm for model                                  
5 creating website using flask, html, bootstrap

In [14]:
import numpy as np
import pandas as pd

In [15]:
ads = pd.read_csv("Social_Network_Ads.csv")

In [16]:
ads.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [17]:
ads.shape

(400, 5)

In [18]:
ads.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [19]:
ads.duplicated().sum()

0

In [20]:
ads.describe()

            User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [21]:
ads['Gender'] = ads['Gender'].map({'Male':1,'Female':0})

In [9]:
from sklearn.model_selection import train_test_split

In [22]:
ads

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510       1   19            19000          0
1    15810944       1   35            20000          0
2    15668575       0   26            43000          0
3    15603246       0   27            57000          0
4    15804002       1   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863       0   46            41000          1
396  15706071       1   51            23000          1
397  15654296       0   50            20000          1
398  15755018       1   36            33000          0
399  15594041       0   49            36000          1

[400 rows x 5 columns]

In [23]:
X_train, X_test, y_train, y_test = train_test_split(ads.drop(['User ID','Purchased'],axis=1),ads['Purchased'], test_size=0.2, random_state=2)

In [24]:
X_train.shape

(320, 3)

In [25]:
X_test.shape

(80, 3)

In [26]:
# scalling

In [30]:
from sklearn.preprocessing import StandardScaler

In [31]:
scalar = StandardScaler()

In [32]:
scalar.fit(X_train)
X_train = scalar.transform(X_train)
X_test = scalar.transform(X_test)

In [33]:
X_train

array([[-0.97530483,  0.88928823, -0.65924556],
       [ 1.02532046, -0.17254846,  0.87392651],
       [-0.97530483, -1.04132394, -0.36440478],
       [ 1.02532046,  0.98581884,  0.6085698 ],
       [ 1.02532046, -0.94479333,  0.57908572],
       [-0.97530483,  0.40663519,  0.01888824],
       [ 1.02532046,  0.98581884,  2.11225779],
       [ 1.02532046,  0.31010458, -0.30543662],
       [ 1.02532046,  1.7580637 , -0.27595254],
       [ 1.02532046, -0.17254846,  2.20071003],
       [-0.97530483,  1.7580637 ,  1.0213469 ],
       [ 1.02532046, -1.33091576, -1.48479975],
       [-0.97530483,  2.04765553,  0.54960165],
       [-0.97530483,  1.27541066,  1.90586924],
       [ 1.02532046, -1.13785454,  0.31372902],
       [-0.97530483, -0.36560968, -0.77718187],
       [ 1.02532046, -1.71703819,  0.49063349],
       [ 1.02532046, -0.5586709 , -1.51428383],
       [ 1.02532046,  0.31010458, -0.71821372],
       [-0.97530483,  0.02051275, -0.57079333],
       [ 1.02532046,  0.02051275,  0.04837232],
       [ 1.02532046, -0.07601785, -0.51182517],
       [ 1.02532046, -0.6552015 , -1.51428383],
       [-0.97530483,  0.02051275,  0.31372902],
       [-0.97530483,  0.31010458,  0.07785639],
       [ 1.02532046, -0.46214029, -1.13099081],
       [ 1.02532046, -0.75173211, -1.54376791],
       [-0.97530483, -0.26907907, -0.65924556],
       [ 1.02532046, -1.13785454,  0.49063349],
       [ 1.02532046, -0.07601785,  2.20071003],
       [ 1.02532046,  0.02051275,  0.04837232],
       [ 1.02532046, -1.13785454, -1.57325199],
       [ 1.02532046,  1.08234944,  0.54960165],
       [ 1.02532046, -0.26907907, -1.24892713],
       [-0.97530483,  1.37194127, -0.92460227],
       [-0.97530483, -1.42744637, -1.21944305],
       [-0.97530483, -0.94479333, -0.95408634],
       [-0.97530483,  1.95112492, -0.65924556],
       [-0.97530483,  0.88928823, -0.57079333],
       [-0.97530483, -1.13785454,  0.31372902],
       [ 1.02532046,  0.02051275, -0.24646847],
       [-0.97530483,  0.79275762, -1.39634752],
       [-0.97530483, -0.26907907, -0.36440478],
       [-0.97530483,  0.88928823,  1.2867036 ],
       [-0.97530483,  0.31010458, -0.18750031],
       [ 1.02532046, -0.26907907, -0.57079333],
       [ 1.02532046, -0.26907907, -1.39634752],
       [-0.97530483,  1.46847188, -1.04253858],
       [ 1.02532046, -0.07601785,  0.13682455],
       [-0.97530483, -0.84826272, -0.65924556],
       [ 1.02532046, -0.07601785,  0.01888824],
       [ 1.02532046, -0.26907907,  0.10734047],
       [ 1.02532046,  0.21357397, -0.30543662],
       [ 1.02532046, -0.26907907,  0.28424494],
       [ 1.02532046,  0.11704336,  0.04837232],
       [ 1.02532046,  1.95112492,  2.20071003],
       [ 1.02532046, -1.04132394, -1.45531567],
       [-0.97530483,  0.31010458,  0.31372902],
       [-0.97530483,  2.04765553, -1.18995897],
       [-0.97530483, -1.13785454, -0.51182517],
       [ 1.02532046,  0.21357397,  0.16630863],
       [ 1.02532046, -0.26907907, -0.92460227],
       [-0.97530483, -0.6552015 ,  0.04837232],
       [-0.97530483,  0.21357397,  0.07785639],
       [ 1.02532046,  0.40663519, -0.12853215],
       [ 1.02532046, -1.13785454, -1.10150673],
       [-0.97530483, -0.07601785,  2.25967818],
       [ 1.02532046,  1.08234944, -0.12853215],
       [ 1.02532046,  0.88928823,  1.05083098],
       [ 1.02532046, -0.07601785,  0.28424494],
       [ 1.02532046, -0.5586709 , -1.51428383],
       [-0.97530483, -1.13785454, -1.0130545 ],
       [-0.97530483, -0.75173211,  1.37515584],
       [ 1.02532046,  1.08234944,  0.57908572],
       [-0.97530483,  1.56500249, -1.2784112 ],
       [-0.97530483,  0.69622701, -1.39634752],
       [-0.97530483, -0.6552015 , -1.04253858],
       [-0.97530483,  1.17888005,  0.54960165],
       [ 1.02532046, -0.26907907, -1.45531567],
       [ 1.02532046, -1.62050759,  0.54960165],
       [-0.97530483, -1.04132394, -1.13099081],
       [-0.97530483, -0.07601785,  0.04837232],
       [-0.97530483,  0.31010458,  0.07785639],
       [ 1.02532046,  0.88928823, -1.36686344],
       [-0.97530483, -1.04132394, -0.3349207 ],
       [ 1.02532046, -1.8135688 ,  0.19579271],
       [-0.97530483, -1.8135688 , -1.4258316 ],
       [-0.97530483,  0.69622701,  1.81741701],
       [-0.97530483, -0.07601785,  0.31372902],
       [ 1.02532046, -1.62050759,  0.07785639],
       [-0.97530483, -0.6552015 ,  1.43412399],
       [ 1.02532046, -0.26907907, -0.24646847],
       [ 1.02532046, -0.36560968,  1.34567176],
       [-0.97530483,  0.5031658 ,  1.25721952],
       [ 1.02532046, -0.6552015 ,  0.19579271],
       [-0.97530483, -1.52397698, -0.42337294],
       [-0.97530483, -1.04132394,  0.43166533],
       [ 1.02532046,  0.79275762,  0.28424494],
       [-0.97530483,  1.95112492, -0.92460227],
       [ 1.02532046,  0.79275762, -0.30543662],
       [ 1.02532046,  0.21357397,  0.25476086],
       [ 1.02532046, -1.71703819, -0.60027741],
       [ 1.02532046, -0.26907907,  0.16630863],
       [-0.97530483, -1.33091576, -1.24892713],
       [ 1.02532046, -0.26907907, -0.42337294],
       [-0.97530483,  0.11704336,  0.10734047],
       [-0.97530483, -0.94479333,  0.46114941],
       [-0.97530483,  2.04765553,  0.40218125],
       [ 1.02532046, -1.91009941,  0.37269718],
       [-0.97530483,  2.04765553, -0.80666595],
       [-0.97530483,  2.14418614,  1.13928321],
       [ 1.02532046,  0.79275762, -1.21944305],
       [ 1.02532046,  0.40663519, -0.45285701],
       [ 1.02532046,  0.02051275, -0.24646847],
       [-0.97530483,  1.46847188,  0.37269718],
       [-0.97530483, -0.17254846, -0.57079333],
       [ 1.02532046,  0.21357397, -0.24646847],
       [-0.97530483, -0.46214029,  2.34813042],
       [ 1.02532046,  0.11704336,  0.22527679],
       [ 1.02532046,  0.21357397, -0.65924556],
       [ 1.02532046,  0.98581884, -1.07202266],
       [-0.97530483, -0.17254846,  0.16630863],
       [-0.97530483, -0.07601785,  0.31372902],
       [-0.97530483,  0.40663519, -0.48234109],
       [-0.97530483, -0.36560968, -1.30789528],
       [ 1.02532046,  0.88928823, -0.77718187],
       [-0.97530483, -0.94479333,  0.43166533],
       [ 1.02532046, -0.07601785, -0.42337294],
       [-0.97530483, -0.94479333, -0.42337294],
       [ 1.02532046, -1.8135688 ,  0.46114941],
       [-0.97530483, -0.84826272, -1.21944305],
       [ 1.02532046, -0.94479333, -0.30543662],
       [-0.97530483,  0.98581884,  0.78547427],
       [-0.97530483, -1.62050759, -0.04007992],
       [ 1.02532046, -1.04132394, -0.3349207 ],
       [ 1.02532046,  0.02051275, -0.54130925],
       [ 1.02532046, -0.6552015 , -0.3349207 ],
       [-0.97530483, -1.13785454, -1.54376791],
       [-0.97530483,  1.95112492, -1.36686344],
       [-0.97530483, -0.6552015 , -1.60273606],
       [ 1.02532046,  0.21357397, -0.36440478],
       [-0.97530483,  0.88928823,  2.20071003],
       [-0.97530483,  1.17888005, -0.98357042],
       [ 1.02532046, -0.17254846, -0.51182517],
       [-0.97530483,  1.66153309,  1.78793293],
       [ 1.02532046,  1.08234944, -1.21944305],
       [-0.97530483,  0.02051275,  1.2867036 ],
       [-0.97530483, -0.46214029, -0.27595254],
       [ 1.02532046,  1.66153309, -0.89511819],
       [ 1.02532046,  0.31010458,  0.52011757],
       [-0.97530483, -1.04132394, -1.54376791],
       [-0.97530483,  1.56500249,  1.13928321],
       [ 1.02532046, -1.52397698,  0.3432131 ],
       [-0.97530483,  0.02051275, -0.12853215],
       [ 1.02532046,  0.11704336, -0.80666595],
       [ 1.02532046,  0.21357397,  1.10979913],
       [ 1.02532046,  0.40663519, -0.15801623],
       [-0.97530483, -0.46214029, -0.01059584],
       [-0.97530483,  1.08234944,  2.11225779],
       [-0.97530483, -0.26907907, -0.12853215],
       [ 1.02532046, -0.75173211, -0.60027741],
       [-0.97530483,  1.17888005, -1.45531567],
       [ 1.02532046, -1.42744637, -1.45531567],
       [ 1.02532046,  1.85459431, -0.27595254],
       [ 1.02532046,  1.85459431,  0.13682455],
       [-0.97530483,  0.40663519,  0.16630863],
       [ 1.02532046,  1.27541066, -1.36686344],
       [-0.97530483, -0.46214029, -1.21944305],
       [ 1.02532046, -0.75173211,  1.93535332],
       [ 1.02532046, -0.26907907,  1.13928321],
       [-0.97530483,  0.02051275, -0.57079333],
       [ 1.02532046,  0.21357397, -0.12853215],
       [-0.97530483, -0.5586709 ,  1.93535332],
       [ 1.02532046, -0.94479333,  0.28424494],
       [-0.97530483, -1.91009941,  0.49063349],
       [-0.97530483, -1.33091576,  0.57908572],
       [-0.97530483,  0.21357397,  0.16630863],
       [-0.97530483,  1.37194127, -1.4258316 ],
       [-0.97530483, -0.07601785,  0.69702204],
       [ 1.02532046,  0.11704336,  1.90586924],
       [-0.97530483, -1.71703819, -0.98357042],
       [ 1.02532046,  0.21357397, -0.36440478],
       [ 1.02532046, -1.8135688 , -1.30789528],
       [ 1.02532046,  0.79275762,  0.54960165],
       [ 1.02532046, -0.17254846,  1.43412399],
       [ 1.02532046, -1.04132394,  0.57908572],
       [ 1.02532046, -1.23438515, -1.07202266],
       [-0.97530483,  1.37194127,  2.02380556],
       [-0.97530483,  0.79275762, -1.10150673],
       [-0.97530483,  0.79275762,  0.13682455],
       [-0.97530483, -1.8135688 , -1.2784112 ],
       [-0.97530483,  0.02051275,  1.25721952],
       [-0.97530483,  0.88928823, -0.60027741],
       [ 1.02532046,  2.14418614,  0.40218125],
       [ 1.02532046,  2.14418614, -0.80666595],
       [ 1.02532046,  0.98581884, -1.07202266],
       [ 1.02532046,  0.11704336,  1.55206031],
       [-0.97530483, -0.94479333,  0.52011757],
       [ 1.02532046, -1.23438515,  0.28424494],
       [-0.97530483,  0.40663519,  0.6085698 ],
       [-0.97530483,  0.11704336,  0.16630863],
       [ 1.02532046,  0.21357397,  0.04837232],
       [ 1.02532046,  2.04765553,  2.17122595],
       [-0.97530483, -0.07601785, -0.36440478],
       [-0.97530483, -0.26907907,  0.81495835],
       [ 1.02532046, -1.42744637, -0.18750031],
       [ 1.02532046,  1.08234944,  0.13682455],
       [-0.97530483,  0.31010458,  0.07785639],
       [-0.97530483,  0.11704336,  0.04837232],
       [-0.97530483,  0.98581884, -1.0130545 ],
       [ 1.02532046, -0.5586709 ,  1.49309215],
       [ 1.02532046, -1.13785454, -1.60273606],
       [-0.97530483,  1.27541066,  2.25967818],
       [-0.97530483, -1.42744637, -0.09904808],
       [ 1.02532046, -1.8135688 , -1.48479975],
       [-0.97530483,  0.88928823, -1.16047489],
       [-0.97530483,  2.14418614, -0.68872964],
       [-0.97530483,  0.5996964 , -0.89511819],
       [ 1.02532046, -1.23438515, -1.39634752],
       [-0.97530483, -0.46214029, -0.83615003],
       [ 1.02532046, -0.84826272, -0.24646847],
       [-0.97530483,  1.46847188,  2.17122595],
       [ 1.02532046,  0.40663519,  1.0213469 ],
       [-0.97530483,  0.02051275, -0.42337294],
       [ 1.02532046, -1.13785454, -1.16047489],
       [ 1.02532046, -0.75173211,  0.57908572],
       [ 1.02532046,  0.11704336,  1.08031505],
       [-0.97530483, -0.5586709 ,  1.40463991],
       [-0.97530483,  0.11704336,  1.90586924],
       [-0.97530483,  0.21357397,  2.14174187],
       [-0.97530483,  1.46847188,  1.0213469 ],
       [ 1.02532046, -1.71703819,  0.13682455],
       [ 1.02532046, -0.26907907, -0.48234109],
       [ 1.02532046,  0.11704336,  0.78547427],
       [ 1.02532046,  0.88928823, -1.30789528],
       [-0.97530483, -0.26907907, -0.27595254],
       [ 1.02532046,  2.14418614, -1.04253858],
       [-0.97530483,  0.40663519,  0.31372902],
       [ 1.02532046, -0.17254846,  1.64051254],
       [-0.97530483,  0.79275762, -0.83615003],
       [ 1.02532046, -0.94479333,  1.58154438],
       [-0.97530483,  0.11704336, -0.24646847],
       [ 1.02532046, -1.23438515,  0.52011757],
       [ 1.02532046,  0.11704336, -0.80666595],
       [-0.97530483,  1.08234944, -0.98357042],
       [-0.97530483,  0.98581884,  1.81741701],
       [-0.97530483, -1.42744637, -0.62976148],
       [-0.97530483,  0.98581884, -1.18995897],
       [ 1.02532046, -1.33091576, -0.42337294],
       [ 1.02532046,  0.31010458,  0.07785639],
       [-0.97530483, -0.26907907, -0.57079333],
       [ 1.02532046, -0.75173211,  1.10979913],
       [-0.97530483,  1.56500249,  1.0213469 ],
       [ 1.02532046, -1.04132394,  0.6085698 ],
       [ 1.02532046,  0.40663519,  0.10734047],
       [-0.97530483, -0.94479333, -0.30543662],
       [-0.97530483,  1.17888005, -0.7476978 ],
       [ 1.02532046, -1.91009941, -0.51182517],
       [ 1.02532046,  1.08234944, -1.21944305],
       [ 1.02532046,  0.31010458,  0.28424494],
       [ 1.02532046, -0.75173211, -1.60273606],
       [-0.97530483, -0.26907907, -1.30789528],
       [ 1.02532046, -0.26907907,  0.54960165],
       [-0.97530483,  0.98581884,  1.90586924],
       [ 1.02532046, -0.6552015 , -0.09904808],
       [-0.97530483, -0.46214029,  1.2867036 ],
       [ 1.02532046,  0.31010458, -0.51182517],
       [-0.97530483,  1.85459431,  1.55206031],
       [ 1.02532046,  1.08234944,  0.49063349],
       [-0.97530483,  2.04765553,  0.19579271],
       [-0.97530483, -1.71703819,  0.37269718],
       [-0.97530483, -0.17254846, -0.18750031],
       [-0.97530483, -0.6552015 ,  0.57908572],
       [-0.97530483,  1.37194127,  1.31618768],
       [-0.97530483,  1.08234944, -0.89511819],
       [-0.97530483,  1.85459431, -1.07202266],
       [ 1.02532046, -0.75173211,  0.52011757],
       [-0.97530483, -1.33091576, -1.10150673],
       [-0.97530483,  0.79275762,  0.37269718],
       [-0.97530483, -0.84826272,  0.40218125],
       [ 1.02532046, -0.75173211,  0.31372902],
       [-0.97530483, -1.04132394,  1.99432148],
       [ 1.02532046, -0.07601785,  0.07785639],
       [ 1.02532046,  1.37194127,  2.3776145 ],
       [ 1.02532046, -0.07601785,  0.16630863],
       [-0.97530483, -0.07601785,  1.99432148],
       [-0.97530483, -0.75173211,  0.28424494],
       [ 1.02532046, -1.13785454,  0.3432131 ],
       [-0.97530483,  0.31010458, -0.27595254],
       [-0.97530483,  0.98581884, -1.16047489],
       [-0.97530483,  1.37194127,  0.6085698 ],
       [ 1.02532046, -1.52397698, -1.51428383],
       [-0.97530483, -0.94479333, -0.7476978 ],
       [-0.97530483, -1.13785454,  0.07785639],
       [ 1.02532046,  0.40663519, -0.45285701],
       [-0.97530483, -1.91009941, -0.7476978 ],
       [-0.97530483,  0.40663519,  0.28424494],
       [-0.97530483, -0.26907907,  0.22527679],
       [-0.97530483, -0.5586709 ,  0.49063349],
       [ 1.02532046, -0.36560968, -0.77718187],
       [-0.97530483, -0.26907907,  0.04837232],
       [ 1.02532046, -0.07601785,  0.22527679],
       [ 1.02532046, -0.26907907,  0.16630863],
       [-0.97530483,  0.31010458, -0.54130925],
       [-0.97530483,  0.79275762,  0.78547427],
       [-0.97530483,  0.98581884,  2.02380556],
       [ 1.02532046, -0.17254846, -0.27595254],
       [-0.97530483, -1.04132394, -0.45285701],
       [ 1.02532046, -0.26907907, -0.3349207 ],
       [-0.97530483,  0.11704336, -0.30543662],
       [-0.97530483, -0.26907907, -0.7476978 ],
       [-0.97530483, -0.07601785, -1.07202266],
       [-0.97530483, -0.26907907,  0.07785639],
       [ 1.02532046,  0.5031658 ,  1.75844885],
       [ 1.02532046, -0.36560968,  1.25721952],
       [ 1.02532046,  0.79275762,  1.40463991],
       [ 1.02532046,  0.98581884, -0.83615003],
       [-0.97530483, -1.71703819, -1.36686344],
       [ 1.02532046, -0.84826272,  0.31372902],
       [ 1.02532046, -0.84826272,  2.31864634]])

In [34]:
# TRainning models

In [36]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

In [37]:
models = {
    "lg":LogisticRegression(),
    'dtc': DecisionTreeClassifier(),
    'rfc': RandomForestClassifier(),
    'gnb': GaussianNB()
}

for name, algo in models.items():
    algo.fit(X_train,y_train)
    y_pred = algo.predict(X_test)
    
    print(f"{name} with accuracy {accuracy_score(y_test,y_pred)}")

lg with accuracy 0.8125
dtc with accuracy 0.8375
rfc with accuracy 0.875
gnb with accuracy 0.8375

In [38]:
rfc = RandomForestClassifier()
rfc.fit(X_train,y_train)
y_pred = rfc.predict(X_test)
accuracy_score(y_test,y_pred)

0.8875

In [48]:
X_train[150]

array([-0.97530483, -1.04132394, -1.54376791])

In [49]:
input_text = (-0.97530483, -1.04132394, -1.54376791)
input_np_text = np.asarray(input_text)
predicion = rfc.predict(input_np_text.reshape(1,-1))
if predicion == 1:
    print("purchased")
else:
    print("Not purchased")

Not purchased

In [ ]:
import pickle
pickle.dump(r)